### ISSUE TITLE
youtube-dl cannot find download link

### ISSUE THREAD

**Issue by karanrajpal14** [Algram/ytdl-webserver#28]
Tried running `npm i` and it fails while installing youtube-dl:
```
> youtube-dl@1.11.1 postinstall /home/karan/projects/ytdl-server/node_modules/youtube-dl
> node ./scripts/download.js

Error: Could not find download link in https://rg3.github.io/youtube-dl/download.html
    at Request.get [as _callback] (/home/karan/projects/ytdl-server/node_modules/youtube-dl/lib/downloader.js:64:31)
    at Request.self.callback (/home/karan/projects/ytdl-server/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/karan/projects/ytdl-server/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/karan/projects/ytdl-server/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Any idea what's going wrong?

**Comment by Algram** [comment]
Hi @karanrajpal14, could you try it with the latest master version of this repo? I've updated the dependencies and this could have very well fix your issue!
